# Generated by Django 4.1.1 on 2022-12-28 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitems',
            old_name='item_name',
            new_name='name',
        ),
    ]
