# Generated by Django 4.1.1 on 2022-12-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_inventoryitems_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitems',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryitems',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
