# Generated by Django 4.1.1 on 2022-12-30 08:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_mobile', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=500)),
                ('customer_mailid', models.EmailField(max_length=254)),
                ('customer_address', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='itemsales',
            name='customer_address',
        ),
        migrations.RemoveField(
            model_name='itemsales',
            name='customer_mailid',
        ),
        migrations.RemoveField(
            model_name='itemsales',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='itemsales',
            name='id',
        ),
        migrations.AddField(
            model_name='itemsales',
            name='order_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemsales',
            name='order_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemsales',
            name='sales_date',
            field=models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False),
        ),
    ]
