# Generated by Django 4.1.1 on 2022-12-30 19:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_customers_remove_itemsales_customer_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('order_status', models.CharField(max_length=20)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_total', models.IntegerField(default=0)),
                ('customer_mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.customers')),
            ],
        ),
        migrations.DeleteModel(
            name='ItemSales',
        ),
    ]
