# Generated by Django 4.1.1 on 2023-01-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_cart_cgst_alter_cart_item_net_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='tax',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='itemsales',
            name='tax',
            field=models.FloatField(default=0),
        ),
    ]
