# Generated by Django 4.1.1 on 2023-01-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_cart_tax_itemsales_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_total',
            field=models.FloatField(default=0),
        ),
    ]
