# Generated by Django 4.1.1 on 2023-01-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_orders_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='item_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='tax',
            field=models.FloatField(default=0),
        ),
    ]
