# Generated by Django 4.1.1 on 2023-01-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_orders_item_price_orders_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='transaction_id',
            field=models.CharField(default='XXXX', max_length=100),
        ),
    ]
