# Generated by Django 4.1.1 on 2023-01-26 03:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_orders_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='bu',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemsales',
            name='bu',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventorygroups',
            name='bu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.businessunit'),
        ),
        migrations.AddField(
            model_name='inventoryitems',
            name='bu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.businessunit'),
        ),
    ]
