# Generated by Django 4.1.1 on 2023-10-22 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_cart_igst_inventoryitems_igst_itemsales_igst'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='exp_date',
            field=models.DateField(default=datetime.date(1111, 11, 11)),
        ),
        migrations.AlterField(
            model_name='inventoryitems',
            name='exp_date',
            field=models.DateField(default=datetime.date(1111, 11, 11)),
        ),
    ]
