# Generated by Django 4.1.1 on 2023-10-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_cart_exp_date_alter_inventoryitems_exp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='gift',
            field=models.BooleanField(default=False),
        ),
    ]
