# Generated by Django 4.1.1 on 2023-11-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_cart_exp_date_alter_inventoryitems_exp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitems',
            name='damage',
            field=models.BooleanField(default=False),
        ),
    ]
