# Generated by Django 4.1.1 on 2023-11-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_inventoryitems_damage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='damage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemsales',
            name='damage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='damage',
            field=models.BooleanField(default=False),
        ),
    ]
