# Generated by Django 4.1.1 on 2022-12-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_itemsales'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsales',
            name='item_price',
            field=models.IntegerField(default=0),
        ),
    ]
