# Generated by Django 4.1.1 on 2022-12-28 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_item_name_inventoryitems_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitems',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.inventorygroups'),
        ),
    ]
