# Generated by Django 4.1.1 on 2023-01-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_itemsales_item_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitems',
            old_name='quantity',
            new_name='available_quantity',
        ),
        migrations.AddField(
            model_name='cart',
            name='cgst',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='item_net_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='sgst',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='unit',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryitems',
            name='cgst',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryitems',
            name='sgst',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryitems',
            name='unit',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='itemsales',
            name='cgst',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemsales',
            name='item_net_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemsales',
            name='sgst',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemsales',
            name='unit',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='orders',
            name='cash',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='online',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(),
        ),
    ]
