# Generated by Django 4.1.1 on 2023-01-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_quantity_inventoryitems_available_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cgst',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='item_net_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='item_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='order_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='sgst',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='inventoryitems',
            name='cgst',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='inventoryitems',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='inventoryitems',
            name='sgst',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='itemsales',
            name='cgst',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='itemsales',
            name='item_net_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='itemsales',
            name='item_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='itemsales',
            name='order_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='itemsales',
            name='sgst',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='cash',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='online',
            field=models.FloatField(default=0),
        ),
    ]
